### ISSUE TITLE
have you seen freezer.js?

### ISSUE THREAD

**Issue by leeoniya** [barneycarroll/patchinko#2]
hey @barneycarroll 

check out https://github.com/arqex/freezer

**Comment by barneycarroll** [comment]
Freezer looks pretty cool. Like Immutable.js with batteries included at 1/10 of the size! Patchinko doesn't have anywhere near that level of opinion or functionality – it's just an isomorphic API for mutating objects.

**Comment by leeoniya** [comment]
> isomorphic API

?

**Comment by barneycarroll** [comment]
[Bad use of the word](http://raganwald.com/2016/12/27/recursive-data-structures.html#fn:isomorphic), sorry. The value proposition of Patchinko is that you can patch an object in a deep, declarative, point-free manner. 'Isomorphism' was a clumsy attempt at describing the fact that the patch looks like the structure it is patching - in contrast to traditional imperative mutation operations & functional idioms where the action is more verbose than the shape & content of patch itself.
