### ISSUE TITLE
Cannot patch null immutably

### ISSUE THREAD

**Issue by robinchew** [barneycarroll/patchinko#25]
```javascript
const thing = {
  val1: undefined,
  val2: null,
}
 
p(O(thing, {val1: O(v => v || 'value')}))
p(O(thing, {val2: O(v => v || 'value')}))
```
The last line fails with:
```
Cannot read property 'constructor' of null
```
[flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9GIAEELAAdaAJ2KTgABQqTVAZQ0ARDVtaSwC2lkkByWRmLVCENAGtaYmAA9ZUCNQjF8WfgsAHTQZeSVJAHljU3MrGzsHZzEZLABXYgwAI1h-QJCQiUktMxhJDAUs3wUKgE9JOGIFNOpiNIUYEKFGyWJ7NABzSQBeFRDJSQA3DCgARkRJNLQAExhINBhlinGpmYAmBbQ0qChttFZxkNkACkjrvocBjWBpuYW7yZGAPinJAB8-pZXmkYBYAJSsMFgq63e79J4qV4HKLXT7DH6fAFAmYg8GQsGUEBwGCwVoQegIHgABkQAGY2BwQJgcHh8NQ4AIaPRGMweGwALqsIA)

**Comment by foxdonut** [comment]
I think just line 36 of immutable.js has to change to:

```javascript
typeof a[key] != null && a[key] == 'object'
```

[flems](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIAW94AcyoHoCBXAOxwGsBzAOlgHsBbAnAQ3lgwEtSL6ABACw0AjDQAMBLo0bF4rAEYwaAKzAgANCABmXGOtQBtUKVaMIaEDSyMomkA1KInlkAF8NJsxfSr1Wx2d4SyIAAgBlJghQ1gAnBS54WLiAT1CwJOIEYliIAB1SRwzQ+G5SKlCAXlDgAtDQgDdWKBFUULIkCF1SZA06xuaAJjbSYigoPtI3OoKcAAoAeTnSnioNGqaWtqWGqoA+RtCAHyPQgHJN4ggzgEo3G5vZxeWytY2h7bndyoPdk-PLtc7g93J4QKZzJY6GB-A56E4IC50O4ALpaKA8CgGYzg7yWaSyeRKCB+ew5OzoLC4fBEMiUWgMZhsDhlPhCUQSKQyOSKZRqezwFI4HzgWCxLg4YJaZmcCDYwyGcRaIUQejaGKGCgQFIokBowwiLShACE1VG41CADJLRqtTq9RpFUbKtUzvQFCo4PAzg7BoINIJBhoAOwAZkNYZEKLR4GgXq48IMIFDAFZUOJUW4gA)

**Comment by barneycarroll** [comment]
Could even get away with this, I think?

```js
a[key] && typeof a[key] == 'object'
```

**Comment by foxdonut** [comment]
I think so, yes.
